Tests for the Shift Model version-1
OurTimeForTech/shiftwork2 pull request #86
Opened 2021-05-09 23:51 UTC by GabrielleEaston

## What type of PR is this? (check all applicable)

- [] Feature
- [] Refactor
- [] Bug Fix
- [] Optimization
- [] Documentation Update
- [x] Other (describe: tests )

## Description of what PR does

- added tests to the Shift Model version-1

- Some tests are failing.

- I am not sure what is the best way to approach the testing of the private method

## Related PRs and/or Issues (if any)
- issue #6 
-

## QA Instructions, Screenshots, Recordings
run ``` bundle exec rspec spec/models/shift_spec.rb  ```

## Added tests?

- [x] yes
- [ ] no, because they aren't needed _(please include reasons for why tests aren't needed)_
- [ ] no, because I need help
- [ ] no, they will be added later (please create an Issue for it)

## Added to documentation?

- [ ] Yes, project README
- [x] No documentation needed

2021-05-10 01:29 UTC, msarit requested changes
GREAT first pass, Gabrielle! You're almost there!

I'm going to modify both the `shift.rb` (Shift model file) and `shifts.rb` (Shift factory); these changes will make some of your specs pass. Bravo - the way you wrote the specs on lines 12 and 14 led to these improvements in the code - which is the purpose of tests! 🎉

2021-05-10 01:37 UTC, GabrielleEaston commented
@aritamana Thank you so much for reviewing! ❤️ I will continue working on it and make the requested changes tomorrow.

2021-05-11 20:04 UTC, msarit commented on spec/models/shift_spec.rb
> +  describe "can_be_dropped?" do
@GabrielleEaston Looks like you overlooked this 😄

2021-05-11 20:11 UTC, msarit requested changes
Almost there! 😅  A few changes to make

2021-05-11 20:11 UTC, GabrielleEaston commented on spec/models/shift_spec.rb
> +    it { is_expected.to validate_presence_of(:shift_start) }
Thank you!

2021-05-11 20:25 UTC, msarit requested changes

2021-05-11 20:25 UTC, msarit commented on spec/models/shift_spec.rb
> +    expect(sample_worker.user_id === sample_user.id).to be(true)
@GabrielleEaston Hmmm I'm still seeing the old expectation 🤔 

I'm expecting (no pun intended) to see something like:

```ruby
expect(sample_shift.filled_by.....).to be(true)
```

Complete the expression inside the `expect()` 👍🏾

2021-05-11 20:35 UTC, msarit approved these changes

2021-05-11 20:36 UTC, merged